Repository tw-group-1/carango-bom-api-base, pull requests merged in 2021-07, with the labels that each got.

#4 change database configuration and organize pipeline
  .github/workflows/development.yml
  src/main/java/br/com/caelum/carangobom/config/database/MySQLConfiguration.java
  src/main/java/br/com/caelum/carangobom/config/database/PostgreConfiguration.java
Labels: enhancement

#5 fix database connection and implementing singleton
  pom.xml
  src/main/java/br/com/caelum/carangobom/config/database/PostgreConfiguration.java
  src/main/java/br/com/caelum/carangobom/controller/BrandController.java
  src/main/java/br/com/caelum/carangobom/repository/BrandRepositoryImpl.java
  src/main/java/br/com/caelum/carangobom/utils/DateFormatter.java
Labels: enhancement

#7 implementing findAll, findById, create tests and create Swagger Doc
  pom.xml
  src/main/java/br/com/caelum/carangobom/controller/BrandController.java
  src/main/java/br/com/caelum/carangobom/domain/Brand.java
  src/main/java/br/com/caelum/carangobom/exception/BrandDuplicatedNameException.java
  src/main/java/br/com/caelum/carangobom/exception/BrandNotFoundException.java
  src/main/java/br/com/caelum/carangobom/exception/BusinessException.java
  src/main/java/br/com/caelum/carangobom/mappers/BrandMappers.java
  src/main/java/br/com/caelum/carangobom/openapi/OpenApiConfig.java
  src/main/java/br/com/caelum/carangobom/repository/BrandRepository.java
  src/main/java/br/com/caelum/carangobom/repository/BrandRepositoryImpl.java
  src/main/java/br/com/caelum/carangobom/utils/Utils.java
  src/main/java/br/com/caelum/carangobom/validacao/ErroDeParametroOutputDto.java
  src/main/java/br/com/caelum/carangobom/validacao/ListaDeErrosOutputDto.java
  src/main/resources/ValidationMessages.properties
  src/main/resources/messages.properties
  src/main/resources/scripts/ddl/ddl.sql
  src/test/java/br/com/caelum/carangobom/BrandMocks.java
  src/test/java/br/com/caelum/carangobom/BrandTests.java
Labels: enhancement

#9 Refactoring brand feature
  .github/workflows/development.yml
  pom.xml
  src/main/java/br/com/caelum/carangobom/controller/BrandController.java
  src/main/java/br/com/caelum/carangobom/domain/Brand.java
  src/main/java/br/com/caelum/carangobom/mappers/BrandMappers.java
  src/main/java/br/com/caelum/carangobom/repository/BrandRepository.java
  src/main/java/br/com/caelum/carangobom/repository/BrandRepositoryImpl.java
  src/main/java/br/com/caelum/carangobom/service/BrandService.java
  src/main/resources/messages.properties
  src/test/java/br/com/caelum/carangobom/BrandTests.java
  src/test/java/br/com/caelum/carangobom/brand/BrandControllerTests.java
  src/test/java/br/com/caelum/carangobom/brand/BrandMocks.java
  src/test/java/br/com/caelum/carangobom/brand/BrandServiceTests.java
Labels: enhancement

#10 change response status code
  pom.xml
  src/main/java/br/com/caelum/carangobom/controller/BrandController.java
  src/test/java/br/com/caelum/carangobom/brand/BrandControllerTests.java
Labels: enhancement

#8 Feature: vehicle crud
  src/main/java/br/com/caelum/carangobom/controller/VehicleController.java
  src/main/java/br/com/caelum/carangobom/controller/request/CreateVehicleRequest.java
  src/main/java/br/com/caelum/carangobom/domain/Vehicle.java
  src/main/java/br/com/caelum/carangobom/exception/VehicleNotFoundException.java
  src/main/java/br/com/caelum/carangobom/mappers/VehicleMappers.java
  src/main/java/br/com/caelum/carangobom/repository/VehicleRepository.java
  src/main/java/br/com/caelum/carangobom/repository/VehicleRepositoryImpl.java
  src/main/java/br/com/caelum/carangobom/service/BrandService.java
  src/main/java/br/com/caelum/carangobom/service/VehicleService.java
  src/main/resources/messages.properties
  src/test/java/br/com/caelum/carangobom/controller/BrandControllerTests.java
  src/test/java/br/com/caelum/carangobom/controller/VehicleControllerTest.java
  src/test/java/br/com/caelum/carangobom/mocks/BrandMocks.java
  src/test/java/br/com/caelum/carangobom/mocks/VehicleMocks.java
  src/test/java/br/com/caelum/carangobom/service/BrandServiceTests.java
  src/test/java/br/com/caelum/carangobom/service/VehicleServiceTest.java
Labels: in progress

#11 fix attribute name on body
  src/main/java/br/com/caelum/carangobom/controller/BrandController.java
  src/main/java/br/com/caelum/carangobom/service/BrandService.java
  src/test/java/br/com/caelum/carangobom/service/BrandServiceTests.java
Labels: bug, documentation

#13 Coverage
  lombok.config
  pom.xml
  src/main/java/br/com/caelum/carangobom/config/database/PostgreConfiguration.java
  src/main/java/br/com/caelum/carangobom/domain/Vehicle.java
  src/main/java/br/com/caelum/carangobom/mappers/VehicleMappers.java
  src/test/java/br/com/caelum/carangobom/service/BrandServiceTests.java
  src/test/java/br/com/caelum/carangobom/service/VehicleServiceTest.java
Labels: in progress

#15 implementing user crud
  src/main/java/br/com/caelum/carangobom/controller/UserController.java
  src/main/java/br/com/caelum/carangobom/controller/VehicleController.java
  src/main/java/br/com/caelum/carangobom/domain/User.java
  src/main/java/br/com/caelum/carangobom/exception/UserNotFoundException.java
  src/main/java/br/com/caelum/carangobom/mappers/UserRowMapper.java
  src/main/java/br/com/caelum/carangobom/repository/UserRepository.java
  src/main/java/br/com/caelum/carangobom/repository/UserRepositoryImpl.java
  src/main/java/br/com/caelum/carangobom/requests/CreateUpdateUserRequest.java
  src/main/java/br/com/caelum/carangobom/requests/CreateVehicleRequest.java
  src/main/java/br/com/caelum/carangobom/service/UserService.java
  src/test/java/br/com/caelum/carangobom/controller/VehicleControllerTest.java
  src/test/java/br/com/caelum/carangobom/mocks/UserMocks.java
  src/test/java/br/com/caelum/carangobom/service/UserServiceTests.java
Labels: enhancement

#16 fix implementation of UserController
  src/main/java/br/com/caelum/carangobom/controller/UserController.java
  src/main/java/br/com/caelum/carangobom/repository/UserRepository.java
  src/main/java/br/com/caelum/carangobom/repository/UserRepositoryImpl.java
Labels: enhancement

#17 fix create method
  src/main/java/br/com/caelum/carangobom/controller/UserController.java
  src/main/java/br/com/caelum/carangobom/exception/UserDuplicatedException.java
  src/main/java/br/com/caelum/carangobom/repository/UserRepository.java
  src/main/java/br/com/caelum/carangobom/repository/UserRepositoryImpl.java
  src/main/java/br/com/caelum/carangobom/service/UserService.java
  src/main/resources/messages.properties
  src/test/java/br/com/caelum/carangobom/service/UserServiceTests.java
Labels: enhancement

#18 implementing dashboard endpoint
  src/main/java/br/com/caelum/carangobom/controller/DashboardController.java
  src/main/java/br/com/caelum/carangobom/controller/VehicleController.java
  src/main/java/br/com/caelum/carangobom/domain/Dashboard.java
  src/main/java/br/com/caelum/carangobom/mappers/DashboardRowMapper.java
  src/main/java/br/com/caelum/carangobom/repository/VehicleRepository.java
  src/main/java/br/com/caelum/carangobom/repository/VehicleRepositoryImpl.java
  src/main/java/br/com/caelum/carangobom/service/VehicleService.java
  src/test/java/br/com/caelum/carangobom/mocks/DashboardMocks.java
  src/test/java/br/com/caelum/carangobom/service/VehicleServiceTest.java
Labels: enhancement

#6 Feature: Authentication and Authorization
  pom.xml
  src/main/java/br/com/caelum/carangobom/config/database/PostgreConfiguration.java
  src/main/java/br/com/caelum/carangobom/config/security/AuthTokenFilter.java
  src/main/java/br/com/caelum/carangobom/config/security/SecurityConfiguration.java
  src/main/java/br/com/caelum/carangobom/controller/AuthController.java
  src/main/java/br/com/caelum/carangobom/controller/dto/LoginDTO.java
  src/main/java/br/com/caelum/carangobom/controller/dto/TokenDTO.java
  src/main/java/br/com/caelum/carangobom/domain/Roles.java
  src/main/java/br/com/caelum/carangobom/domain/User.java
  src/main/java/br/com/caelum/carangobom/mappers/UserRowMapper.java
  src/main/java/br/com/caelum/carangobom/repository/BrandRepository.java
  src/main/java/br/com/caelum/carangobom/repository/UserRepository.java
  src/main/java/br/com/caelum/carangobom/repository/UserRepositoryImpl.java
  src/main/java/br/com/caelum/carangobom/service/AuthService.java
  src/main/java/br/com/caelum/carangobom/service/TokenService.java
  src/main/java/br/com/caelum/carangobom/service/UserService.java
  src/main/resources/application.properties
  src/test/java/br/com/caelum/carangobom/controller/BrandControllerTests.java
  src/test/java/br/com/caelum/carangobom/controller/VehicleControllerTest.java
  src/test/java/br/com/caelum/carangobom/mocks/UserMocks.java
  src/test/java/br/com/caelum/carangobom/service/BrandServiceTests.java
  src/test/java/br/com/caelum/carangobom/service/UserServiceTests.java
  src/test/java/br/com/caelum/carangobom/service/VehicleServiceTest.java
Labels: in progress

#19 Coverage
  pom.xml
  src/main/java/br/com/caelum/carangobom/config/openapi/OpenApiConfig.java
  src/main/java/br/com/caelum/carangobom/config/security/SecurityConfiguration.java
Labels: enhancement

#20 improve sonar coverage
  pom.xml
  src/main/java/br/com/caelum/carangobom/controller/VehicleController.java
  src/main/java/br/com/caelum/carangobom/service/UserService.java
  src/test/java/br/com/caelum/carangobom/controller/UserControllerTests.java
  src/test/java/br/com/caelum/carangobom/mocks/VehicleMocks.java
  src/test/java/br/com/caelum/carangobom/service/AuthServiceTest.java
Labels: enhancement

#21 fix code smells
  src/main/java/br/com/caelum/carangobom/config/security/SecurityConfiguration.java
  src/main/java/br/com/caelum/carangobom/service/TokenService.java
Labels: enhancement
